#!/usr/bin/env ruby
# frozen_string_literal: true

require 'create_github_release'

options = CreateGithubRelease::CommandLine::Parser.new.parse(*ARGV)
pp options if options.verbose

project = CreateGithubRelease::Project.new(options)

CreateGithubRelease::ReleaseAssertions.new(project).make_assertions
puts unless options.quiet
CreateGithubRelease::ReleaseTasks.new(project).run

puts <<~MESSAGE unless project.quiet
  SUCCESS: created release '#{project.next_release_tag}'

  Next steps:

  * Review the release notes:

  #{project.release_url}

  * Get someone to review and approve the release pull request:

  #{project.release_pr_url}

  * Merge the pull request manually from the command line with the following
    commands:

  git checkout #{project.default_branch}
  git merge --ff-only #{project.release_branch}
  git push

  * Wait for the CI build to pass on the default branch and then release the
    gem with the following command:

  rake release:rubygem_push

MESSAGE
