name: Experimental Ruby Builds

on:
  push:
    branches: [main]

  workflow_dispatch:

# Experimental platforms / Ruby versions:
#  - Ubuntu: MRI (head), TruffleRuby (head), JRuby (head)
#  - Windows: MRI (head), JRuby (head)

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}
    
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: head
            operating-system: ubuntu-latest
          - ruby: head
            operating-system: windows-latest
          - ruby: truffleruby-head
            operating-system: ubuntu-latest
          - ruby: jruby-head
            operating-system: ubuntu-latest
          - ruby: jruby-head
            operating-system: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake
