name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', 'head']

    name: Build on Ruby ${{ matrix.ruby }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake

  coverage:
    needs: [ build ]
    runs-on: ubuntu-latest

    name: Report test coverage to CodeClimate

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true


      - name: Report test coverage
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: 89aff99f016ae5eb4bc5437c5e1b1ea6ffaacd8b20cea6b4873288a822bdb9ee
        with:
          coverageCommand: bundle exec rake spec
          coverageLocations: ${{github.workspace}}/coverage/lcov/*.lcov:lcov
